version: "3.6"

volumes:
  pg_data:
    driver: local

networks:
  backend:
    driver: bridge

services:
  postgres:
    image: postgres:latest
    container_name: backend_majoo_test
    environment:
      - POSTGRES_DB=majoo
      - POSTGRES_PASSWORD=qweasd123
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5449:5432
    networks:
      - backend
